target 'AXCGiphy', :exclusive => true do
  pod "AXCGiphy", :path => "../"
  pod 'AFNetworking/Serialization', '~> 2.3.1'
end

target 'Tests', :exclusive => true do
  pod "AXCGiphy", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
